<?php

namespace didi\carrera\consumer\proxy;
/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 * @generated
 */

use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;


interface ConsumerServiceIf
{
    /**
     * @param \didi\carrera\consumer\proxy\PullRequest $request
     * @return \didi\carrera\consumer\proxy\PullResponse
     * @throws \didi\carrera\consumer\proxy\PullException
     */
    public function pull(\didi\carrera\consumer\proxy\PullRequest $request);

    /**
     * @param \didi\carrera\consumer\proxy\ConsumeResult $result
     * @return bool
     * @throws \didi\carrera\consumer\proxy\PullException
     */
    public function submit(\didi\carrera\consumer\proxy\ConsumeResult $result);

    /**
     * @param \didi\carrera\consumer\proxy\ConsumeStatsRequest $request
     * @return \didi\carrera\consumer\proxy\ConsumeStats[]
     * @throws \didi\carrera\consumer\proxy\PullException
     */
    public function getConsumeStats(\didi\carrera\consumer\proxy\ConsumeStatsRequest $request);

    /**
     * @param \didi\carrera\consumer\proxy\FetchRequest $request
     * @return \didi\carrera\consumer\proxy\FetchResponse
     */
    public function fetch(\didi\carrera\consumer\proxy\FetchRequest $request);

    /**
     * @param \didi\carrera\consumer\proxy\AckResult $result
     * @return bool
     */
    public function ack(\didi\carrera\consumer\proxy\AckResult $result);
}

class ConsumerServiceClient implements \didi\carrera\consumer\proxy\ConsumerServiceIf
{
    protected $input_ = null;
    protected $output_ = null;

    protected $seqid_ = 0;

    public function __construct($input, $output = null)
    {
        $this->input_ = $input;
        $this->output_ = $output ? $output : $input;
    }

    public function pull(\didi\carrera\consumer\proxy\PullRequest $request)
    {
        $this->send_pull($request);
        return $this->recv_pull();
    }

    public function send_pull(\didi\carrera\consumer\proxy\PullRequest $request)
    {
        $args = new \didi\carrera\consumer\proxy\ConsumerService_pull_args();
        $args->request = $request;
        $this->send_base("pull", $args);
    }

    public function recv_pull()
    {
        $result = new \didi\carrera\consumer\proxy\ConsumerService_pull_result();
        return $this->receive_base($result, "pull");
    }

    public function submit(\didi\carrera\consumer\proxy\ConsumeResult $result)
    {
        $this->send_submit($result);
        return $this->recv_submit();
    }

    public function send_submit(\didi\carrera\consumer\proxy\ConsumeResult $result)
    {
        $args = new \didi\carrera\consumer\proxy\ConsumerService_submit_args();
        $args->result = $result;
        $this->send_base("submit", $args);
    }

    public function recv_submit()
    {
        $result = new \didi\carrera\consumer\proxy\ConsumerService_submit_result();
        return $this->receive_base($result, "submit");
    }

    public function getConsumeStats(\didi\carrera\consumer\proxy\ConsumeStatsRequest $request)
    {
        $this->send_getConsumeStats($request);
        return $this->recv_getConsumeStats();
    }

    public function send_getConsumeStats(\didi\carrera\consumer\proxy\ConsumeStatsRequest $request)
    {
        $args = new \didi\carrera\consumer\proxy\ConsumerService_getConsumeStats_args();
        $args->request = $request;
        $this->send_base("getConsumeStats", $args);
    }

    public function recv_getConsumeStats()
    {
        $result = new \didi\carrera\consumer\proxy\ConsumerService_getConsumeStats_result();
        return $this->receive_base($result, "getConsumeStats");
    }

    public function fetch(\didi\carrera\consumer\proxy\FetchRequest $request)
    {
        $this->send_fetch($request);
        return $this->recv_fetch();
    }

    public function send_fetch(\didi\carrera\consumer\proxy\FetchRequest $request)
    {
        $args = new \didi\carrera\consumer\proxy\ConsumerService_fetch_args();
        $args->request = $request;
        $this->send_base("fetch", $args);
    }

    public function recv_fetch()
    {
        $result = new \didi\carrera\consumer\proxy\ConsumerService_fetch_result();
        return $this->receive_base($result, "fetch");
    }

    public function ack(\didi\carrera\consumer\proxy\AckResult $result)
    {
        $this->send_ack($result);
        return $this->recv_ack();
    }

    public function send_ack(\didi\carrera\consumer\proxy\AckResult $result)
    {
        $args = new \didi\carrera\consumer\proxy\ConsumerService_ack_args();
        $args->result = $result;
        $this->send_base("ack", $args);
    }

    public function recv_ack()
    {
        $result = new \didi\carrera\consumer\proxy\ConsumerService_ack_result();
        return $this->receive_base($result, "ack");
    }

    public function send_base($cmd, $args)
    {
        $this->output_->writeMessageBegin($cmd, TMessageType::CALL, $this->seqid_);
        $args->write($this->output_);
        $this->output_->writeMessageEnd();
        $this->output_->getTransport()->flush();
    }

    public function receive_base($result, $cmd)
    {
        $rseqid = 0;
        $fname = null;
        $mtype = 0;
        $this->input_->readMessageBegin($fname, $mtype, $rseqid);
        if ($mtype == TMessageType::EXCEPTION) {
            $x = new TApplicationException();
            $x->read($this->input_);
            $this->input_->readMessageEnd();
            throw $x;
        }
        $result->read($this->input_);
        $this->input_->readMessageEnd();
        if ($result->success !== null) {
            return $result->success;
        }
        if ($result->error !== null) {
            throw $result->error;
        }
        throw new \Exception("$cmd failed: unknown result");
    }
}

// HELPER FUNCTIONS AND STRUCTURES

class ConsumerService_pull_args
{
    static $_TSPEC;

    /**
     * @var \didi\carrera\consumer\proxy\PullRequest
     */
    public $request = null;

    public function __construct($vals = null)
    {
        if (!isset(self::$_TSPEC)) {
            self::$_TSPEC = array(
                1 => array(
                    'var' => 'request',
                    'type' => TType::STRUCT,
                    'class' => '\didi\carrera\consumer\proxy\PullRequest',
                ),
            );
        }
        if (is_array($vals)) {
            if (isset($vals['request'])) {
                $this->request = $vals['request'];
            }
        }
    }

    public function getName()
    {
        return 'ConsumerService_pull_args';
    }

    public function read($input)
    {
        $xfer = 0;
        $fname = null;
        $ftype = 0;
        $fid = 0;
        $xfer += $input->readStructBegin($fname);
        while (true) {
            $xfer += $input->readFieldBegin($fname, $ftype, $fid);
            if ($ftype == TType::STOP) {
                break;
            }
            switch ($fid) {
                case 1:
                    if ($ftype == TType::STRUCT) {
                        $this->request = new \didi\carrera\consumer\proxy\PullRequest();
                        $xfer += $this->request->read($input);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                default:
                    $xfer += $input->skip($ftype);
                    break;
            }
            $xfer += $input->readFieldEnd();
        }
        $xfer += $input->readStructEnd();
        return $xfer;
    }

    public function write($output)
    {
        $xfer = 0;
        $xfer += $output->writeStructBegin('ConsumerService_pull_args');
        if ($this->request !== null) {
            if (!is_object($this->request)) {
                throw new TProtocolException('Bad type in structure.', TProtocolException::INVALID_DATA);
            }
            $xfer += $output->writeFieldBegin('request', TType::STRUCT, 1);
            $xfer += $this->request->write($output);
            $xfer += $output->writeFieldEnd();
        }
        $xfer += $output->writeFieldStop();
        $xfer += $output->writeStructEnd();
        return $xfer;
    }

}

class ConsumerService_pull_result
{
    static $_TSPEC;

    /**
     * @var \didi\carrera\consumer\proxy\PullResponse
     */
    public $success = null;
    /**
     * @var \didi\carrera\consumer\proxy\PullException
     */
    public $error = null;

    public function __construct($vals = null)
    {
        if (!isset(self::$_TSPEC)) {
            self::$_TSPEC = array(
                0 => array(
                    'var' => 'success',
                    'type' => TType::STRUCT,
                    'class' => '\didi\carrera\consumer\proxy\PullResponse',
                ),
                1 => array(
                    'var' => 'error',
                    'type' => TType::STRUCT,
                    'class' => '\didi\carrera\consumer\proxy\PullException',
                ),
            );
        }
        if (is_array($vals)) {
            if (isset($vals['success'])) {
                $this->success = $vals['success'];
            }
            if (isset($vals['error'])) {
                $this->error = $vals['error'];
            }
        }
    }

    public function getName()
    {
        return 'ConsumerService_pull_result';
    }

    public function read($input)
    {
        $xfer = 0;
        $fname = null;
        $ftype = 0;
        $fid = 0;
        $xfer += $input->readStructBegin($fname);
        while (true) {
            $xfer += $input->readFieldBegin($fname, $ftype, $fid);
            if ($ftype == TType::STOP) {
                break;
            }
            switch ($fid) {
                case 0:
                    if ($ftype == TType::STRUCT) {
                        $this->success = new \didi\carrera\consumer\proxy\PullResponse();
                        $xfer += $this->success->read($input);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 1:
                    if ($ftype == TType::STRUCT) {
                        $this->error = new \didi\carrera\consumer\proxy\PullException();
                        $xfer += $this->error->read($input);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                default:
                    $xfer += $input->skip($ftype);
                    break;
            }
            $xfer += $input->readFieldEnd();
        }
        $xfer += $input->readStructEnd();
        return $xfer;
    }

    public function write($output)
    {
        $xfer = 0;
        $xfer += $output->writeStructBegin('ConsumerService_pull_result');
        if ($this->success !== null) {
            if (!is_object($this->success)) {
                throw new TProtocolException('Bad type in structure.', TProtocolException::INVALID_DATA);
            }
            $xfer += $output->writeFieldBegin('success', TType::STRUCT, 0);
            $xfer += $this->success->write($output);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->error !== null) {
            $xfer += $output->writeFieldBegin('error', TType::STRUCT, 1);
            $xfer += $this->error->write($output);
            $xfer += $output->writeFieldEnd();
        }
        $xfer += $output->writeFieldStop();
        $xfer += $output->writeStructEnd();
        return $xfer;
    }

}

class ConsumerService_submit_args
{
    static $_TSPEC;

    /**
     * @var \didi\carrera\consumer\proxy\ConsumeResult
     */
    public $result = null;

    public function __construct($vals = null)
    {
        if (!isset(self::$_TSPEC)) {
            self::$_TSPEC = array(
                1 => array(
                    'var' => 'result',
                    'type' => TType::STRUCT,
                    'class' => '\didi\carrera\consumer\proxy\ConsumeResult',
                ),
            );
        }
        if (is_array($vals)) {
            if (isset($vals['result'])) {
                $this->result = $vals['result'];
            }
        }
    }

    public function getName()
    {
        return 'ConsumerService_submit_args';
    }

    public function read($input)
    {
        $xfer = 0;
        $fname = null;
        $ftype = 0;
        $fid = 0;
        $xfer += $input->readStructBegin($fname);
        while (true) {
            $xfer += $input->readFieldBegin($fname, $ftype, $fid);
            if ($ftype == TType::STOP) {
                break;
            }
            switch ($fid) {
                case 1:
                    if ($ftype == TType::STRUCT) {
                        $this->result = new \didi\carrera\consumer\proxy\ConsumeResult();
                        $xfer += $this->result->read($input);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                default:
                    $xfer += $input->skip($ftype);
                    break;
            }
            $xfer += $input->readFieldEnd();
        }
        $xfer += $input->readStructEnd();
        return $xfer;
    }

    public function write($output)
    {
        $xfer = 0;
        $xfer += $output->writeStructBegin('ConsumerService_submit_args');
        if ($this->result !== null) {
            if (!is_object($this->result)) {
                throw new TProtocolException('Bad type in structure.', TProtocolException::INVALID_DATA);
            }
            $xfer += $output->writeFieldBegin('result', TType::STRUCT, 1);
            $xfer += $this->result->write($output);
            $xfer += $output->writeFieldEnd();
        }
        $xfer += $output->writeFieldStop();
        $xfer += $output->writeStructEnd();
        return $xfer;
    }

}

class ConsumerService_submit_result
{
    static $_TSPEC;

    /**
     * @var bool
     */
    public $success = null;
    /**
     * @var \didi\carrera\consumer\proxy\PullException
     */
    public $error = null;

    public function __construct($vals = null)
    {
        if (!isset(self::$_TSPEC)) {
            self::$_TSPEC = array(
                0 => array(
                    'var' => 'success',
                    'type' => TType::BOOL,
                ),
                1 => array(
                    'var' => 'error',
                    'type' => TType::STRUCT,
                    'class' => '\didi\carrera\consumer\proxy\PullException',
                ),
            );
        }
        if (is_array($vals)) {
            if (isset($vals['success'])) {
                $this->success = $vals['success'];
            }
            if (isset($vals['error'])) {
                $this->error = $vals['error'];
            }
        }
    }

    public function getName()
    {
        return 'ConsumerService_submit_result';
    }

    public function read($input)
    {
        $xfer = 0;
        $fname = null;
        $ftype = 0;
        $fid = 0;
        $xfer += $input->readStructBegin($fname);
        while (true) {
            $xfer += $input->readFieldBegin($fname, $ftype, $fid);
            if ($ftype == TType::STOP) {
                break;
            }
            switch ($fid) {
                case 0:
                    if ($ftype == TType::BOOL) {
                        $xfer += $input->readBool($this->success);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 1:
                    if ($ftype == TType::STRUCT) {
                        $this->error = new \didi\carrera\consumer\proxy\PullException();
                        $xfer += $this->error->read($input);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                default:
                    $xfer += $input->skip($ftype);
                    break;
            }
            $xfer += $input->readFieldEnd();
        }
        $xfer += $input->readStructEnd();
        return $xfer;
    }

    public function write($output)
    {
        $xfer = 0;
        $xfer += $output->writeStructBegin('ConsumerService_submit_result');
        if ($this->success !== null) {
            $xfer += $output->writeFieldBegin('success', TType::BOOL, 0);
            $xfer += $output->writeBool($this->success);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->error !== null) {
            $xfer += $output->writeFieldBegin('error', TType::STRUCT, 1);
            $xfer += $this->error->write($output);
            $xfer += $output->writeFieldEnd();
        }
        $xfer += $output->writeFieldStop();
        $xfer += $output->writeStructEnd();
        return $xfer;
    }

}

class ConsumerService_getConsumeStats_args
{
    static $_TSPEC;

    /**
     * @var \didi\carrera\consumer\proxy\ConsumeStatsRequest
     */
    public $request = null;

    public function __construct($vals = null)
    {
        if (!isset(self::$_TSPEC)) {
            self::$_TSPEC = array(
                1 => array(
                    'var' => 'request',
                    'type' => TType::STRUCT,
                    'class' => '\didi\carrera\consumer\proxy\ConsumeStatsRequest',
                ),
            );
        }
        if (is_array($vals)) {
            if (isset($vals['request'])) {
                $this->request = $vals['request'];
            }
        }
    }

    public function getName()
    {
        return 'ConsumerService_getConsumeStats_args';
    }

    public function read($input)
    {
        $xfer = 0;
        $fname = null;
        $ftype = 0;
        $fid = 0;
        $xfer += $input->readStructBegin($fname);
        while (true) {
            $xfer += $input->readFieldBegin($fname, $ftype, $fid);
            if ($ftype == TType::STOP) {
                break;
            }
            switch ($fid) {
                case 1:
                    if ($ftype == TType::STRUCT) {
                        $this->request = new \didi\carrera\consumer\proxy\ConsumeStatsRequest();
                        $xfer += $this->request->read($input);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                default:
                    $xfer += $input->skip($ftype);
                    break;
            }
            $xfer += $input->readFieldEnd();
        }
        $xfer += $input->readStructEnd();
        return $xfer;
    }

    public function write($output)
    {
        $xfer = 0;
        $xfer += $output->writeStructBegin('ConsumerService_getConsumeStats_args');
        if ($this->request !== null) {
            if (!is_object($this->request)) {
                throw new TProtocolException('Bad type in structure.', TProtocolException::INVALID_DATA);
            }
            $xfer += $output->writeFieldBegin('request', TType::STRUCT, 1);
            $xfer += $this->request->write($output);
            $xfer += $output->writeFieldEnd();
        }
        $xfer += $output->writeFieldStop();
        $xfer += $output->writeStructEnd();
        return $xfer;
    }

}

class ConsumerService_getConsumeStats_result
{
    static $_TSPEC;

    /**
     * @var \didi\carrera\consumer\proxy\ConsumeStats[]
     */
    public $success = null;
    /**
     * @var \didi\carrera\consumer\proxy\PullException
     */
    public $error = null;

    public function __construct($vals = null)
    {
        if (!isset(self::$_TSPEC)) {
            self::$_TSPEC = array(
                0 => array(
                    'var' => 'success',
                    'type' => TType::LST,
                    'etype' => TType::STRUCT,
                    'elem' => array(
                        'type' => TType::STRUCT,
                        'class' => '\didi\carrera\consumer\proxy\ConsumeStats',
                    ),
                ),
                1 => array(
                    'var' => 'error',
                    'type' => TType::STRUCT,
                    'class' => '\didi\carrera\consumer\proxy\PullException',
                ),
            );
        }
        if (is_array($vals)) {
            if (isset($vals['success'])) {
                $this->success = $vals['success'];
            }
            if (isset($vals['error'])) {
                $this->error = $vals['error'];
            }
        }
    }

    public function getName()
    {
        return 'ConsumerService_getConsumeStats_result';
    }

    public function read($input)
    {
        $xfer = 0;
        $fname = null;
        $ftype = 0;
        $fid = 0;
        $xfer += $input->readStructBegin($fname);
        while (true) {
            $xfer += $input->readFieldBegin($fname, $ftype, $fid);
            if ($ftype == TType::STOP) {
                break;
            }
            switch ($fid) {
                case 0:
                    if ($ftype == TType::LST) {
                        $this->success = array();
                        $_size98 = 0;
                        $_etype101 = 0;
                        $xfer += $input->readListBegin($_etype101, $_size98);
                        for ($_i102 = 0; $_i102 < $_size98; ++$_i102) {
                            $elem103 = null;
                            $elem103 = new \didi\carrera\consumer\proxy\ConsumeStats();
                            $xfer += $elem103->read($input);
                            $this->success [] = $elem103;
                        }
                        $xfer += $input->readListEnd();
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 1:
                    if ($ftype == TType::STRUCT) {
                        $this->error = new \didi\carrera\consumer\proxy\PullException();
                        $xfer += $this->error->read($input);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                default:
                    $xfer += $input->skip($ftype);
                    break;
            }
            $xfer += $input->readFieldEnd();
        }
        $xfer += $input->readStructEnd();
        return $xfer;
    }

    public function write($output)
    {
        $xfer = 0;
        $xfer += $output->writeStructBegin('ConsumerService_getConsumeStats_result');
        if ($this->success !== null) {
            if (!is_array($this->success)) {
                throw new TProtocolException('Bad type in structure.', TProtocolException::INVALID_DATA);
            }
            $xfer += $output->writeFieldBegin('success', TType::LST, 0);
            {
                $output->writeListBegin(TType::STRUCT, count($this->success));
                {
                    foreach ($this->success as $iter104) {
                        $xfer += $iter104->write($output);
                    }
                }
                $output->writeListEnd();
            }
            $xfer += $output->writeFieldEnd();
        }
        if ($this->error !== null) {
            $xfer += $output->writeFieldBegin('error', TType::STRUCT, 1);
            $xfer += $this->error->write($output);
            $xfer += $output->writeFieldEnd();
        }
        $xfer += $output->writeFieldStop();
        $xfer += $output->writeStructEnd();
        return $xfer;
    }

}

class ConsumerService_fetch_args
{
    static $_TSPEC;

    /**
     * @var \didi\carrera\consumer\proxy\FetchRequest
     */
    public $request = null;

    public function __construct($vals = null)
    {
        if (!isset(self::$_TSPEC)) {
            self::$_TSPEC = array(
                1 => array(
                    'var' => 'request',
                    'type' => TType::STRUCT,
                    'class' => '\didi\carrera\consumer\proxy\FetchRequest',
                ),
            );
        }
        if (is_array($vals)) {
            if (isset($vals['request'])) {
                $this->request = $vals['request'];
            }
        }
    }

    public function getName()
    {
        return 'ConsumerService_fetch_args';
    }

    public function read($input)
    {
        $xfer = 0;
        $fname = null;
        $ftype = 0;
        $fid = 0;
        $xfer += $input->readStructBegin($fname);
        while (true) {
            $xfer += $input->readFieldBegin($fname, $ftype, $fid);
            if ($ftype == TType::STOP) {
                break;
            }
            switch ($fid) {
                case 1:
                    if ($ftype == TType::STRUCT) {
                        $this->request = new \didi\carrera\consumer\proxy\FetchRequest();
                        $xfer += $this->request->read($input);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                default:
                    $xfer += $input->skip($ftype);
                    break;
            }
            $xfer += $input->readFieldEnd();
        }
        $xfer += $input->readStructEnd();
        return $xfer;
    }

    public function write($output)
    {
        $xfer = 0;
        $xfer += $output->writeStructBegin('ConsumerService_fetch_args');
        if ($this->request !== null) {
            if (!is_object($this->request)) {
                throw new TProtocolException('Bad type in structure.', TProtocolException::INVALID_DATA);
            }
            $xfer += $output->writeFieldBegin('request', TType::STRUCT, 1);
            $xfer += $this->request->write($output);
            $xfer += $output->writeFieldEnd();
        }
        $xfer += $output->writeFieldStop();
        $xfer += $output->writeStructEnd();
        return $xfer;
    }

}

class ConsumerService_fetch_result
{
    static $_TSPEC;

    /**
     * @var \didi\carrera\consumer\proxy\FetchResponse
     */
    public $success = null;

    public function __construct($vals = null)
    {
        if (!isset(self::$_TSPEC)) {
            self::$_TSPEC = array(
                0 => array(
                    'var' => 'success',
                    'type' => TType::STRUCT,
                    'class' => '\didi\carrera\consumer\proxy\FetchResponse',
                ),
            );
        }
        if (is_array($vals)) {
            if (isset($vals['success'])) {
                $this->success = $vals['success'];
            }
        }
    }

    public function getName()
    {
        return 'ConsumerService_fetch_result';
    }

    public function read($input)
    {
        $xfer = 0;
        $fname = null;
        $ftype = 0;
        $fid = 0;
        $xfer += $input->readStructBegin($fname);
        while (true) {
            $xfer += $input->readFieldBegin($fname, $ftype, $fid);
            if ($ftype == TType::STOP) {
                break;
            }
            switch ($fid) {
                case 0:
                    if ($ftype == TType::STRUCT) {
                        $this->success = new \didi\carrera\consumer\proxy\FetchResponse();
                        $xfer += $this->success->read($input);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                default:
                    $xfer += $input->skip($ftype);
                    break;
            }
            $xfer += $input->readFieldEnd();
        }
        $xfer += $input->readStructEnd();
        return $xfer;
    }

    public function write($output)
    {
        $xfer = 0;
        $xfer += $output->writeStructBegin('ConsumerService_fetch_result');
        if ($this->success !== null) {
            if (!is_object($this->success)) {
                throw new TProtocolException('Bad type in structure.', TProtocolException::INVALID_DATA);
            }
            $xfer += $output->writeFieldBegin('success', TType::STRUCT, 0);
            $xfer += $this->success->write($output);
            $xfer += $output->writeFieldEnd();
        }
        $xfer += $output->writeFieldStop();
        $xfer += $output->writeStructEnd();
        return $xfer;
    }

}

class ConsumerService_ack_args
{
    static $_TSPEC;

    /**
     * @var \didi\carrera\consumer\proxy\AckResult
     */
    public $result = null;

    public function __construct($vals = null)
    {
        if (!isset(self::$_TSPEC)) {
            self::$_TSPEC = array(
                1 => array(
                    'var' => 'result',
                    'type' => TType::STRUCT,
                    'class' => '\didi\carrera\consumer\proxy\AckResult',
                ),
            );
        }
        if (is_array($vals)) {
            if (isset($vals['result'])) {
                $this->result = $vals['result'];
            }
        }
    }

    public function getName()
    {
        return 'ConsumerService_ack_args';
    }

    public function read($input)
    {
        $xfer = 0;
        $fname = null;
        $ftype = 0;
        $fid = 0;
        $xfer += $input->readStructBegin($fname);
        while (true) {
            $xfer += $input->readFieldBegin($fname, $ftype, $fid);
            if ($ftype == TType::STOP) {
                break;
            }
            switch ($fid) {
                case 1:
                    if ($ftype == TType::STRUCT) {
                        $this->result = new \didi\carrera\consumer\proxy\AckResult();
                        $xfer += $this->result->read($input);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                default:
                    $xfer += $input->skip($ftype);
                    break;
            }
            $xfer += $input->readFieldEnd();
        }
        $xfer += $input->readStructEnd();
        return $xfer;
    }

    public function write($output)
    {
        $xfer = 0;
        $xfer += $output->writeStructBegin('ConsumerService_ack_args');
        if ($this->result !== null) {
            if (!is_object($this->result)) {
                throw new TProtocolException('Bad type in structure.', TProtocolException::INVALID_DATA);
            }
            $xfer += $output->writeFieldBegin('result', TType::STRUCT, 1);
            $xfer += $this->result->write($output);
            $xfer += $output->writeFieldEnd();
        }
        $xfer += $output->writeFieldStop();
        $xfer += $output->writeStructEnd();
        return $xfer;
    }

}

class ConsumerService_ack_result
{
    static $_TSPEC;

    /**
     * @var bool
     */
    public $success = null;

    public function __construct($vals = null)
    {
        if (!isset(self::$_TSPEC)) {
            self::$_TSPEC = array(
                0 => array(
                    'var' => 'success',
                    'type' => TType::BOOL,
                ),
            );
        }
        if (is_array($vals)) {
            if (isset($vals['success'])) {
                $this->success = $vals['success'];
            }
        }
    }

    public function getName()
    {
        return 'ConsumerService_ack_result';
    }

    public function read($input)
    {
        $xfer = 0;
        $fname = null;
        $ftype = 0;
        $fid = 0;
        $xfer += $input->readStructBegin($fname);
        while (true) {
            $xfer += $input->readFieldBegin($fname, $ftype, $fid);
            if ($ftype == TType::STOP) {
                break;
            }
            switch ($fid) {
                case 0:
                    if ($ftype == TType::BOOL) {
                        $xfer += $input->readBool($this->success);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                default:
                    $xfer += $input->skip($ftype);
                    break;
            }
            $xfer += $input->readFieldEnd();
        }
        $xfer += $input->readStructEnd();
        return $xfer;
    }

    public function write($output)
    {
        $xfer = 0;
        $xfer += $output->writeStructBegin('ConsumerService_ack_result');
        if ($this->success !== null) {
            $xfer += $output->writeFieldBegin('success', TType::BOOL, 0);
            $xfer += $output->writeBool($this->success);
            $xfer += $output->writeFieldEnd();
        }
        $xfer += $output->writeFieldStop();
        $xfer += $output->writeStructEnd();
        return $xfer;
    }
}